"""initial schema

Revision ID: dcdb860f5814
Revises: 
Create Date: 2026-08-22 12:58:34.203325

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0001_initial_schema'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('industry', sa.String(length=255), nullable=True),
    sa.Column('employee_count', sa.Integer(), nullable=True),
    sa.Column('country', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cases',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=True),
    sa.Column('customer_name', sa.String(length=255), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('deadline_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reporting_period_start', sa.Date(), nullable=True),
    sa.Column('reporting_period_end', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('DRAFT', 'PROCESSING', 'IN_REVIEW', 'READY', 'EXPORTED', 'ARCHIVED')", name='ck_cases_status'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('documents',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('case_id', sa.String(length=36), nullable=False),
    sa.Column('original_filename', sa.String(length=500), nullable=False),
    sa.Column('mime_type', sa.String(length=255), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('storage_key', sa.String(length=1000), nullable=False),
    sa.Column('document_type', sa.String(length=30), nullable=False),
    sa.Column('processing_status', sa.String(length=30), nullable=False),
    sa.Column('source_date', sa.Date(), nullable=True),
    sa.Column('period_start', sa.Date(), nullable=True),
    sa.Column('period_end', sa.Date(), nullable=True),
    sa.Column('error_code', sa.String(length=120), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("document_type IN ('QUESTIONNAIRE', 'UTILITY_BILL', 'POLICY', 'HR_DATA', 'WASTE_RECORD', 'SAFETY_RECORD', 'OTHER')", name='ck_documents_type'),
    sa.CheckConstraint("processing_status IN ('UPLOADED', 'PARSING', 'PARSED', 'INDEXED', 'FAILED', 'NEEDS_MANUAL_REVIEW')", name='ck_documents_processing_status'),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('case_id', 'sha256', name='uq_documents_case_sha256')
    )
    op.create_table('document_chunks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('document_id', sa.String(length=36), nullable=False),
    sa.Column('sequence_no', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=True),
    sa.Column('sheet_name', sa.String(length=255), nullable=True),
    sa.Column('cell_range', sa.String(length=60), nullable=True),
    sa.Column('heading_path', sa.Text(), nullable=True),
    sa.Column('metadata_json', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('questionnaires',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('case_id', sa.String(length=36), nullable=False),
    sa.Column('document_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('version', sa.String(length=60), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('questions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('questionnaire_id', sa.String(length=36), nullable=False),
    sa.Column('external_question_id', sa.String(length=120), nullable=True),
    sa.Column('source_location', sa.Text(), nullable=True),
    sa.Column('section', sa.String(length=255), nullable=True),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('is_required', sa.Boolean(), nullable=False),
    sa.Column('pillar', sa.String(length=20), nullable=False),
    sa.Column('sedg_topic_code', sa.String(length=30), nullable=True),
    sa.Column('sedg_disclosure_code', sa.String(length=30), nullable=True),
    sa.Column('mapping_rationale', sa.Text(), nullable=True),
    sa.Column('evidence_requirement_json', sa.Text(), nullable=True),
    sa.Column('question_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("pillar IN ('E', 'S', 'G', 'UNCATEGORIZED')", name='ck_questions_pillar'),
    sa.ForeignKeyConstraint(['questionnaire_id'], ['questionnaires.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('actions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('case_id', sa.String(length=36), nullable=False),
    sa.Column('question_id', sa.String(length=36), nullable=True),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('owner_name', sa.String(length=255), nullable=True),
    sa.Column('owner_role', sa.String(length=120), nullable=True),
    sa.Column('next_step', sa.Text(), nullable=True),
    sa.Column('deadline_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('completion_note', sa.Text(), nullable=True),
    sa.Column('closure_evidence_document_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('TODO', 'IN_PROGRESS', 'BLOCKED', 'NEEDS_REVIEW', 'COMPLETED')", name='ck_actions_status'),
    sa.CheckConstraint("type IN ('SUBMISSION', 'IMPROVEMENT')", name='ck_actions_type'),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.ForeignKeyConstraint(['closure_evidence_document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('answers',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('question_id', sa.String(length=36), nullable=False),
    sa.Column('draft_answer', sa.Text(), nullable=True),
    sa.Column('confirmed_answer', sa.Text(), nullable=True),
    sa.Column('evidence_status', sa.String(length=30), nullable=False),
    sa.Column('status_reason', sa.Text(), nullable=True),
    sa.Column('review_status', sa.String(length=30), nullable=False),
    sa.Column('reviewer_name', sa.String(length=255), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('draft_provenance', sa.String(length=30), nullable=False),
    sa.Column('ai_run_id', sa.String(length=36), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("draft_provenance IN ('NONE', 'AI_GENERATED', 'AI_ASSISTED_EDIT', 'USER_ENTERED')", name='ck_answers_draft_provenance'),
    sa.CheckConstraint("draft_provenance NOT IN ('AI_GENERATED', 'AI_ASSISTED_EDIT') OR ai_run_id IS NOT NULL", name='ck_answers_provenance_ai_run'),
    sa.CheckConstraint("evidence_status IN ('VERIFIED', 'PARTIAL', 'OUTDATED', 'CONFLICTING', 'MISSING', 'NOT_APPLICABLE', 'NEEDS_MANUAL_REVIEW')", name='ck_answers_evidence_status'),
    sa.CheckConstraint("review_status IN ('UNREVIEWED', 'HUMAN_CONFIRMED', 'REJECTED', 'NEEDS_REVISION')", name='ck_answers_review_status'),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('question_id')
    )
    op.create_table('evidence_links',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('question_id', sa.String(length=36), nullable=False),
    sa.Column('answer_id', sa.String(length=36), nullable=True),
    sa.Column('document_id', sa.String(length=36), nullable=False),
    sa.Column('chunk_id', sa.String(length=36), nullable=False),
    sa.Column('location_json', sa.Text(), nullable=False),
    sa.Column('quoted_excerpt', sa.Text(), nullable=True),
    sa.Column('claim_supported', sa.Text(), nullable=True),
    sa.Column('period_start', sa.Date(), nullable=True),
    sa.Column('period_end', sa.Date(), nullable=True),
    sa.Column('scope_description', sa.String(length=500), nullable=True),
    sa.Column('unit', sa.String(length=60), nullable=True),
    sa.Column('link_status', sa.String(length=30), nullable=False),
    sa.Column('created_by', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("created_by IN ('SYSTEM', 'USER')", name='ck_evidence_links_created_by'),
    sa.CheckConstraint("link_status IN ('CANDIDATE', 'ACCEPTED', 'REJECTED', 'INVALIDATED')", name='ck_evidence_links_status'),
    sa.ForeignKeyConstraint(['answer_id'], ['answers.id'], ),
    sa.ForeignKeyConstraint(['chunk_id'], ['document_chunks.id'], ),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('evidence_links')
    op.drop_table('answers')
    op.drop_table('actions')
    op.drop_table('questions')
    op.drop_table('questionnaires')
    op.drop_table('document_chunks')
    op.drop_table('documents')
    op.drop_table('cases')
    op.drop_table('organizations')
    # ### end Alembic commands ###
